# Generated by Django 2.0.7 on 2018-07-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_auto_20180719_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_link',
        ),
        migrations.RemoveField(
            model_name='link',
            name='source_link',
        ),
        migrations.AddField(
            model_name='link',
            name='short_url',
            field=models.CharField(default='no short url', max_length=15),
        ),
        migrations.AddField(
            model_name='link',
            name='source_url',
            field=models.CharField(default='unkown.url', max_length=200),
        ),
    ]
