# Generated by Django 2.0.7 on 2018-07-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0003_auto_20180719_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(default='sho.rt/link', error_messages={'required': ''}, max_length=15),
        ),
        migrations.AlterField(
            model_name='link',
            name='source_url',
            field=models.CharField(default='http://example.com', error_messages={'required': ''}, max_length=200),
        ),
    ]
