# Generated by Django 2.0.7 on 2018-07-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0004_auto_20180719_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(default='liNk1', error_messages={'required': ''}, max_length=15),
        ),
    ]
